export const colorPalette = {
  true: {
    '--page-bg': 'rgb(5, 14, 26)',
    '--page-bg-dark': 'rgb(5, 14, 26)',
    '--page-bg-light': '#fff3e6',

    '--navbar-link-text': 'rgb(234, 243, 255)',
    '--navbar-link-text-hovered': 'rgb(5, 14, 26)',
    '--navbar-link-text-active': 'rgb(5, 14, 26)',
    '--navbar-link-bg': '#25a6e9',
    '--navbar-link-bg-active': 'rgb(168 127 251 / 1)',
    '--text': 'rgb(234, 243, 255)',

    '--footer-separation': 'rgb(234, 243, 255)',
    '--footer-text': 'rgb(234, 243, 255)',

    '--darkMode-button-moon-bg': 'rgb(57, 20, 94)',
    '--darkMode-button-sun-bg': '#696969',
    '--darkMode-button-sun-color': '#353535',

    '--home-title-opacity': '0',

    '--home-subtitle': 'rgb(234, 243, 255)',
    '--home-subtitle-underline': 'rgb(168 127 251 / 1)',
    '--home-text': 'rgb(234, 243, 255)',
    '--home-tecnologies-title': 'rgb(234, 243, 255)',
    '--home-tecnologies-1': '#39c3f5',
    '--home-tecnologies-2': '#000000',
    '--home-tecnologies-3': '#edf036',
    '--home-tecnologies-4': '#ff8c20',
    '--home-tecnologies-5': '#1e78cd',
    '--home-tecnologies-6': '#000000',
    '--home-tecnologies-text-black': 'black',
    '--home-tecnologies-text-white': 'white',
    '--home-stars': 'rgb(234, 243, 255)',
    '--home-estela': 'rgb(234, 243, 255)',

    '--about-title-cell-bg': 'rgb(16 21 29/1)',
    '--about-title-cell-shadow': '#2e3c51',
    '--about-title-cell-text': 'rgb(219, 228, 240)',
    '--about-title-cell-text-random': 'rgba(191, 199, 210, 0.616)',
    '--about-biography-title': 'rgb(234, 243, 255)',
    '--about-biography-text': 'rgb(234, 243, 255)',
    '--about-img-line': 'rgb(234, 243, 255)',
    '--about-biography-background-1': 'linear-gradient(#427480, #427480)',
    '--about-biography-background-2': 'linear-gradient(#3f7958, #3f7958)',
    '--about-biography-background-3': 'linear-gradient(#405f2e, #405f2e)',
    '--about-biography-background-4': 'linear-gradient(#8b7d2d, #8b7d2d)',
    '--about-biography-background-5': 'linear-gradient(#865f2a, #865f2a)',
    '--about-biography-background-6': 'linear-gradient(#7c4339, #7c4339)',
    '--about-skills-title': 'rgb(234, 243, 255)',
    '--about-skills-title-glitch-1': 'rgb(168 127 251)',
    '--about-skills-title-glitch-2': '#25a6e9',
    '--about-skills-card-bg': 'rgb(103, 81, 148)',
    '--about-skills-card-title': 'rgb(26, 13, 53)',
    '--about-skills-card-text': 'rgb(234, 243, 255)',
    '--about-skills-card-circle-1': 'rgb(26, 13, 53)',
    '--about-skills-card-circle-2': '#ffa23e',
    '--about-skills-card-circle-3': '#17b877',

    '--projects-title': 'rgb(234, 243, 255)',
    '--projects-card-title': 'rgb(168 127 251 / 1)',
    '--projects-card-link': 'rgb(234, 243, 255)',
    '--projects-card-text': 'rgb(234, 243, 255)',
    '--projects-card-line': 'rgb(234, 243, 255)',
    '--projects-card-line-under': 'rgb(234, 243, 255)',

    '--contactme-overlay': 'rgba(0, 0, 0, 0.685)',
    '--contactme-title-text': 'rgb(234, 243, 255)',
    '--contactme-title-bg': 'rgb(0, 18, 48)',
    '--contactme-title-bg-error': '#411313',
    '--contactme-title-bg-success': 'rgb(2, 29, 2)',
    '--contactme-message-text': 'rgb(234, 243, 255)',
    '--contactme-message-bg': '#324c5a',
    '--contactme-message-placeholder': 'rgb(188, 198, 211)',
    '--contactme-button-text': 'black',
    '--contactme-button-text-error': '#290605',
    '--contactme-button-text-success': 'rgb(12, 59, 12)',
    '--contactme-button-bg': '#e48124',
    '--contactme-button-bg-error': 'rgb(173, 93, 93)',
    '--contactme-button-bg-success': 'rgb(105, 173, 105)',
    '--contactme-button-loader': 'lightBlue',
    '--contactme-button-loader-spin': 'rgb(16 21 29/1)',
    '--contactme-button-loader-error': 'darkRed',
    '--contactme-button-loader-success': 'green',

    '--transition-time-slow': '.5s',
    '--transition-time-fast': '.25s',
    '--transition-time-project': '.1s',
    '--transition-time-lang': '.4s'
  },
  false: {
    '--page-bg': '#fff3e6',
    '--page-bg-dark': 'rgb(5, 14, 26)',
    '--page-bg-light': '#fff3e6',

    '--navbar-link-text': '#36384C',
    '--navbar-link-text-hovered': 'white',
    '--navbar-link-text-active': 'white',
    '--navbar-link-bg': '#613A43',
    '--navbar-link-bg-active': '#58644e',
    '--text': '#36384C',

    '--footer-separation': '#36384c',
    '--footer-text': '#36384C',

    '--darkMode-button-moon-bg': '#696969',
    '--darkMode-button-sun-bg': 'rgb(254, 234, 172)',
    '--darkMode-button-sun-color': '#FEAD03',

    '--home-title-opacity': '1',

    '--home-subtitle': '#36384C',
    '--home-subtitle-underline': '#849974',
    '--home-text': '#36384C',
    '--home-tecnologies-title': '#36384C',
    '--home-tecnologies-1': '#39c3f5',
    '--home-tecnologies-2': '#000000',
    '--home-tecnologies-3': '#edf036',
    '--home-tecnologies-4': '#ff8c20',
    '--home-tecnologies-5': '#1e78cd',
    '--home-tecnologies-6': '#000000',
    '--home-tecnologies-text-black': 'black',
    '--home-tecnologies-text-white': 'white',
    '--home-stars': '#36384C',
    '--home-estela': '#36384C',

    '--about-title-cell-bg': '#613A43',
    '--about-title-cell-shadow': '#835d66',
    '--about-title-cell-text': '#ffeaef',
    '--about-title-cell-text-random': '#cca1ab7c',
    '--about-biography-title': '#36384C',
    '--about-biography-text': '#36384C',
    '--about-img-line': '#36384C',
    '--about-biography-background-1': 'linear-gradient(#88bcc9, #88bcc9)',
    '--about-biography-background-2': 'linear-gradient(#91d3af, #91d3af)',
    '--about-biography-background-3': 'linear-gradient(#a9d88e, #a9d88e)',
    '--about-biography-background-4': 'linear-gradient(#d3c576, #d3c576)',
    '--about-biography-background-5': 'linear-gradient(#dbb98d, #dbb98d)',
    '--about-biography-background-6': 'linear-gradient(#cf9d94, #cf9d94)',
    '--about-skills-title': '#36384C',
    '--about-skills-title-glitch-1': '#fd527a',
    '--about-skills-title-glitch-2': '#a1fc56',
    '--about-skills-card-bg': '#cee0c2',
    '--about-skills-card-title': '#4e222d',
    '--about-skills-card-text': '#36384C',
    '--about-skills-card-circle-1': '#4e222d',
    '--about-skills-card-circle-2': '#ffff6c',
    '--about-skills-card-circle-3': '#5f6e53',

    '--projects-title': '#36384C',
    '--projects-card-title': '#8f1030',
    '--projects-card-link': '#36384C',
    '--projects-card-text': '#36384C',
    '--projects-card-line': 'rgb(27 27 27/ 1)',
    '--projects-card-line-under': 'black',

    '--contactme-overlay': 'rgba(0, 0, 0, 0.5)',
    '--contactme-title-text': '#041e49',
    '--contactme-title-bg': '#b5c7a7',
    '--contactme-title-bg-error': '#ff8a8a',
    '--contactme-title-bg-success': '#9cf05c',
    '--contactme-message-text': '#36384C',
    '--contactme-message-bg': '#f5ffee',
    '--contactme-message-placeholder': '#4b4e69',
    '--contactme-button-text': '#f5ffee',
    '--contactme-button-text-error': '#ffcccb',
    '--contactme-button-text-success': 'lightGreen',
    '--contactme-button-bg': '#4e222d',
    '--contactme-button-bg-error': 'red',
    '--contactme-button-bg-success': 'green',
    '--contactme-button-loader': 'lightBlue',
    '--contactme-button-loader-spin': 'rgb(255, 255, 255)',
    '--contactme-button-loader-error': 'darkRed',
    '--contactme-button-loader-success': 'green',

    '--transition-time-slow': '1s',
    '--transition-time-fast': '.7s',
    '--transition-time-project': '.8s',
    '--transition-time-lang': '.3s'

  }
}

export const colorPaletteObject = {
  true: [
    { name: '--page-bg', color: 'rgb(5, 14, 26)' },
    { name: '--page-bg-dark', color: 'rgb(5, 14, 26)' },
    { name: '--page-bg-light', color: '#fff3e6' },

    { name: '--navbar-link-text', color: 'rgb(234, 243, 255)' },
    { name: '--navbar-link-text-hovered', color: 'rgb(5, 14, 26)' },
    { name: '--navbar-link-text-active', color: 'rgb(5, 14, 26)' },
    { name: '--navbar-link-bg', color: '#25a6e9' },
    { name: '--navbar-link-bg-active', color: 'rgb(168 127 251 / 1)' },
    { name: '--text', color: 'rgb(234, 243, 255)' },

    { name: '--footer-separation', color: 'rgb(234, 243, 255)' },
    { name: '--footer-text', color: 'rgb(234, 243, 255)' },

    { name: '--darkMode-button-moon-bg', color: 'rgb(57, 20, 94)' },
    { name: '--darkMode-button-sun-bg', color: '#696969' },
    { name: '--darkMode-button-sun-color', color: '#353535' },

    { name: '--home-title-opacity', color: '0' },

    { name: '--home-subtitle', color: 'rgb(234, 243, 255)' },
    { name: '--home-subtitle-underline', color: 'rgb(168 127 251 / 1)' },
    { name: '--home-text', color: 'rgb(234, 243, 255)' },
    { name: '--home-tecnologies-title', color: 'rgb(234, 243, 255)' },
    { name: '--home-tecnologies-1', color: '#39c3f5' },
    { name: '--home-tecnologies-2', color: '#000000' },
    { name: '--home-tecnologies-3', color: '#edf036' },
    { name: '--home-tecnologies-4', color: '#ff8c20' },
    { name: '--home-tecnologies-5', color: '#1e78cd' },
    { name: '--home-tecnologies-6', color: '#000000' },
    { name: '--home-tecnologies-text-black', color: 'black' },
    { name: '--home-tecnologies-text-white', color: 'white' },
    { name: '--home-stars', color: 'rgb(234, 243, 255)' },
    { name: '--home-estela', color: 'rgb(234, 243, 255)' },

    { name: '--about-title-cell-bg', color: 'rgb(16 21 29/1)' },
    { name: '--about-title-cell-shadow', color: '#2e3c51' },
    { name: '--about-title-cell-text', color: 'rgb(219, 228, 240)' },
    { name: '--about-title-cell-text-random', color: 'rgba(191, 199, 210, 0.616)' },
    { name: '--about-biography-title', color: 'rgb(234, 243, 255)' },
    { name: '--about-biography-text', color: 'rgb(234, 243, 255)' },
    { name: '--about-img-line', color: 'rgb(234, 243, 255)' },
    { name: '--about-biography-background-1', color: 'linear-gradient(#427480, #427480)' },
    { name: '--about-biography-background-2', color: 'linear-gradient(#3f7958, #3f7958)' },
    { name: '--about-biography-background-3', color: 'linear-gradient(#405f2e, #405f2e)' },
    { name: '--about-biography-background-4', color: 'linear-gradient(#8b7d2d, #8b7d2d)' },
    { name: '--about-biography-background-5', color: 'linear-gradient(#865f2a, #865f2a)' },
    { name: '--about-biography-background-6', color: 'linear-gradient(#7c4339, #7c4339)' },
    { name: '--about-skills-title', color: 'rgb(234, 243, 255)' },
    { name: '--about-skills-title-glitch-1', color: 'rgb(168 127 251)' },
    { name: '--about-skills-title-glitch-2', color: '#25a6e9' },
    { name: '--about-skills-card-bg', color: 'rgb(103, 81, 148)' },
    { name: '--about-skills-card-title', color: 'rgb(26, 13, 53)' },
    { name: '--about-skills-card-text', color: 'rgb(234, 243, 255)' },
    { name: '--about-skills-card-circle-1', color: 'rgb(26, 13, 53)' },
    { name: '--about-skills-card-circle-2', color: '#ffa23e' },
    { name: '--about-skills-card-circle-3', color: '#17b877' },

    { name: '--projects-title', color: 'rgb(234, 243, 255)' },
    { name: '--projects-card-title', color: 'rgb(168 127 251 / 1)' },
    { name: '--projects-card-link', color: 'rgb(234, 243, 255)' },
    { name: '--projects-card-text', color: 'rgb(234, 243, 255)' },
    { name: '--projects-card-line', color: 'rgb(234, 243, 255)' },
    { name: '--projects-card-line-under', color: 'rgb(234, 243, 255)' },

    { name: '--contactme-overlay', color: 'rgba(0, 0, 0, 0.685)' },
    { name: '--contactme-title-text', color: 'rgb(234, 243, 255)' },
    { name: '--contactme-title-bg', color: 'rgb(0, 18, 48)' },
    { name: '--contactme-title-bg-error', color: '#411313' },
    { name: '--contactme-title-bg-success', color: 'rgb(2, 29, 2)' },
    { name: '--contactme-message-text', color: 'rgb(234, 243, 255)' },
    { name: '--contactme-message-bg', color: '#324c5a' },
    { name: '--contactme-message-placeholder', color: 'rgb(188, 198, 211)' },
    { name: '--contactme-button-text', color: 'black' },
    { name: '--contactme-button-text-error', color: '#290605' },
    { name: '--contactme-button-text-success', color: 'rgb(12, 59, 12)' },
    { name: '--contactme-button-bg', color: '#e48124' },
    { name: '--contactme-button-bg-error', color: 'rgb(173, 93, 93)' },
    { name: '--contactme-button-bg-success', color: 'rgb(105, 173, 105)' },
    { name: '--contactme-button-loader', color: 'lightBlue' },
    { name: '--contactme-button-loader-spin', color: 'rgb(16 21 29/1)' },
    { name: '--contactme-button-loader-error', color: 'darkRed' },
    { name: '--contactme-button-loader-success', color: 'green' },

    { name: '--transition-time-slow', color: '.5s' },
    { name: '--transition-time-fast', color: '.25s' },
    { name: '--transition-time-project', color: '.1s' },
    { name: '--transition-time-lang', color: '.4s' }
  ],
  false: [
    { name: '--page-bg', color: '#fff3e6' },
    { name: '--page-bg-dark', color: 'rgb(5, 14, 26)' },
    { name: '--page-bg-light', color: '#fff3e6' },

    { name: '--navbar-link-text', color: '#36384C' },
    { name: '--navbar-link-text-hovered', color: 'white' },
    { name: '--navbar-link-text-active', color: 'white' },
    { name: '--navbar-link-bg', color: '#613A43' },
    { name: '--navbar-link-bg-active', color: '#58644e' },
    { name: '--text', color: '#36384C' },

    { name: '--footer-separation', color: '#36384c' },
    { name: '--footer-text', color: '#36384C' },

    { name: '--darkMode-button-moon-bg', color: '#696969' },
    { name: '--darkMode-button-sun-bg', color: 'rgb(254, 234, 172)' },
    { name: '--darkMode-button-sun-color', color: '#FEAD03' },

    { name: '--home-title-opacity', color: '1' },

    { name: '--home-subtitle', color: '#36384C' },
    { name: '--home-subtitle-underline', color: '#849974' },
    { name: '--home-text', color: '#36384C' },
    { name: '--home-tecnologies-title', color: '#36384C' },
    { name: '--home-tecnologies-1', color: '#39c3f5' },
    { name: '--home-tecnologies-2', color: '#000000' },
    { name: '--home-tecnologies-3', color: '#edf036' },
    { name: '--home-tecnologies-4', color: '#ff8c20' },
    { name: '--home-tecnologies-5', color: '#1e78cd' },
    { name: '--home-tecnologies-6', color: '#000000' },
    { name: '--home-tecnologies-text-black', color: 'black' },
    { name: '--home-tecnologies-text-white', color: 'white' },
    { name: '--home-stars', color: '#36384C' },
    { name: '--home-estela', color: '#36384C' },

    { name: '--about-title-cell-bg', color: '#613A43' },
    { name: '--about-title-cell-shadow', color: '#835d66' },
    { name: '--about-title-cell-text', color: '#ffeaef' },
    { name: '--about-title-cell-text-random', color: '#cca1ab7c' },
    { name: '--about-biography-title', color: '#36384C' },
    { name: '--about-biography-text', color: '#36384C' },
    { name: '--about-img-line', color: '#36384C' },
    { name: '--about-biography-background-1', color: 'linear-gradient(#88bcc9, #88bcc9)' },
    { name: '--about-biography-background-2', color: 'linear-gradient(#91d3af, #91d3af)' },
    { name: '--about-biography-background-3', color: 'linear-gradient(#a9d88e, #a9d88e)' },
    { name: '--about-biography-background-4', color: 'linear-gradient(#d3c576, #d3c576)' },
    { name: '--about-biography-background-5', color: 'linear-gradient(#dbb98d, #dbb98d)' },
    { name: '--about-biography-background-6', color: 'linear-gradient(#cf9d94, #cf9d94)' },
    { name: '--about-skills-title', color: '#36384C' },
    { name: '--about-skills-title-glitch-1', color: '#fd527a' },
    { name: '--about-skills-title-glitch-2', color: '#a1fc56' },
    { name: '--about-skills-card-bg', color: '#cee0c2' },
    { name: '--about-skills-card-title', color: '#4e222d' },
    { name: '--about-skills-card-text', color: '#36384C' },
    { name: '--about-skills-card-circle-1', color: '#4e222d' },
    { name: '--about-skills-card-circle-2', color: '#ffff6c' },
    { name: '--about-skills-card-circle-3', color: '#5f6e53' },

    { name: '--projects-title', color: '#36384C' },
    { name: '--projects-card-title', color: '#8f1030' },
    { name: '--projects-card-link', color: '#36384C' },
    { name: '--projects-card-text', color: '#36384C' },
    { name: '--projects-card-line', color: 'rgb(27 27 27/ 1)' },
    { name: '--projects-card-line-under', color: 'black' },

    { name: '--contactme-overlay', color: 'rgba(0, 0, 0, 0.5)' },
    { name: '--contactme-title-text', color: '#041e49' },
    { name: '--contactme-title-bg', color: '#b5c7a7' },
    { name: '--contactme-title-bg-error', color: '#ff8a8a' },
    { name: '--contactme-title-bg-success', color: '#9cf05c' },
    { name: '--contactme-message-text', color: '#36384C' },
    { name: '--contactme-message-bg', color: '#f5ffee' },
    { name: '--contactme-message-placeholder', color: '#4b4e69' },
    { name: '--contactme-button-text', color: '#f5ffee' },
    { name: '--contactme-button-text-error', color: '#ffcccb' },
    { name: '--contactme-button-text-success', color: 'lightGreen' },
    { name: '--contactme-button-bg', color: '#4e222d' },
    { name: '--contactme-button-bg-error', color: 'red' },
    { name: '--contactme-button-bg-success', color: 'green' },
    { name: '--contactme-button-loader', color: 'lightBlue' },
    { name: '--contactme-button-loader-spin', color: 'rgb(255, 255, 255)' },
    { name: '--contactme-button-loader-error', color: 'darkRed' },
    { name: '--contactme-button-loader-success', color: 'green' },

    { name: '--transition-time-slow', color: '1s' },
    { name: '--transition-time-fast', color: '.7s' },
    { name: '--transition-time-project', color: '.8s' },
    { name: '--transition-time-lang', color: '.3s' }

  ]
}
